app/admin/forms.py
from wtforms.fields import StringField, PasswordField, SubmitField, TextAreaField
from wtforms.validators import InputRequired
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired, FileAllowed


class LoginForm(FlaskForm):
    username = StringField(
        'Username',
        [InputRequired()]
    )
    password = PasswordField(
        'Password',
        [InputRequired()]
    )
    submit = SubmitField(
        'Submit',
        [InputRequired()]
    )

class PortfolioForm(FlaskForm):
    name = StringField(
        'Name',
        [InputRequired()]
    )
    link = StringField(
        'Link',
        [InputRequired()]
    )
    description = TextAreaField(
        'Description',
        [InputRequired()]
    )
    submit = SubmitField(
        'Submit',
        [InputRequired()]
    )

class BadgeForm(FlaskForm):
    name = StringField(
        'Name',
        [InputRequired()]
    )
    link = StringField(
        'Link',
        [InputRequired()]
    )
    image = FileField(
        'Image',
        validators=[
            FileAllowed(['jpg','png'], 'Images only'),
            FileRequired()
        ]
    )
    submit = SubmitField(
        'Submit',
        [InputRequired()]
    )

app/frontend/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import InputRequired


class ContactForm(FlaskForm):
    contact = StringField(
        'Email or Phone',
        [InputRequired('Enter either an email address or a phone number.')]
    )
    subject = StringField(
        'Subject',
        [InputRequired('Enter a subject.')]
    )
    message = TextAreaField(
        'Message',
        [InputRequired('Enter a message.')]
    )
    submit = SubmitField(
        'Submit'
    )

app/__init__.py
import os
from dotenv import load_dotenv
from flask import Flask, render_template
from flask_wtf import CSRFProtect
from flask_mail import Mail
from flask_login import LoginManager


csrf = CSRFProtect()
mail = Mail()
login_manager = LoginManager()

def create_app():
    app = Flask(__name__)

    load_dotenv()

    app.config['DEBUG'] = True

    app.config['SECRET_KEY'] = os.environ['SECRET_KEY'] or 'none'
    app.config['WTF_CSRF_SECRET_KEY'] = os.environ['WTF_CSRF_SECRET_KEY'] or 'none'
    
    app.config['DATABASE_URI'] = os.environ['DATABASE_URI']
    
    app.config['MAIL_SERVER'] = os.environ['MAIL_SERVER']
    app.config['MAIL_PORT'] = os.environ['MAIL_PORT']
    app.config['MAIL_USERNAME'] = os.environ['MAIL_USERNAME']
    app.config['MAIL_PASSWORD'] = os.environ['MAIL_PASSWORD']
    app.config['DEFAULT_MAIL_SENDER'] = os.environ['DEFAULT_MAIL_SENDER']
    app.config['MAIL_SUBJECT_PREFIX'] = os.environ['MAIL_SUBJECT_PREFIX']
    app.config['MAIL_USE_TLS'] = False
    app.config['MAIL_USE_SSL'] = True

    basedir = os.path.abspath(os.path.dirname(__file__))
    badges_folder = os.path.join(basedir, 'static/images/badges')
    app.config['BADGES_FOLDER'] = badges_folder

    csrf.init_app(app)
    mail.init_app(app)
    login_manager.init_app(app)
    login_manager.login_view = 'admin_blueprint.login'
    login_manager.login_message_category = 'info'

    from app.frontend import frontend_blueprint
    app.register_blueprint(frontend_blueprint)

    from app.admin import admin_blueprint
    app.register_blueprint(admin_blueprint)

    @app.errorhandler(404)
    def page_not_found(e):
        return render_template('404.html'), 404

    return app

app/admin/__init__.py
from flask import Blueprint


admin_blueprint = Blueprint('admin_blueprint', __name__)

from . import views

app/admin/views.py
import os
from dotenv import load_dotenv

from flask import render_template, request, flash, redirect, url_for, current_app
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.utils import secure_filename

from app import login_manager
from ..db.queries import validate_user, get_user_object, create_project, save_img
from . import admin_blueprint as blp
from .forms import LoginForm, PortfolioForm, BadgeForm


@login_manager.user_loader
def load_user(id):
    return get_user_object(int(id))


@blp.route('/mypanel', methods=('GET', 'POST'))
def login():
    form = LoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        username = form.username.data
        password = form.password.data

        user_id = validate_user(username, password)
        if user_id:
            user = load_user(user_id)
            login_user(user)
            return redirect(url_for('.admin_page'))

    return render_template('login.html', form=form)


@blp.route('/admin-page', methods=('GET', 'POST'))
@login_required
def admin_page():
    form1 = PortfolioForm()
    form2 = BadgeForm()
    if request.method == 'POST' and form1.validate_on_submit():
        name = form1.name.data
        link = form1.link.data
        description = form1.description.data

        create_project(name,link,description)
        flash('Project added.', 'success')

        return redirect(url_for('.admin_page'))
    
    elif request.method == 'POST' and form2.validate_on_submit():
        img = form2.image.data
        name = form2.name.data
        link = form2.link.data
        filename = secure_filename(img.filename)

        save_img(name,link,filename)

        img.save(os.path.join(current_app.config['BADGES_FOLDER'], filename))

        return redirect(url_for('.admin_page'))
    
    return render_template('admin-page.html', form1=form1, form2=form2)

app/frontend/__init__.py
from flask import Blueprint


frontend_blueprint = Blueprint('frontend_blueprint', __name__)

from . import views

app/frontend/views.py
import os
from flask import render_template, request, redirect, flash

from . import frontend_blueprint as blp

from ..db.queries import all_projects, all_badges
from .forms import ContactForm
from ..email_function import send_email

@blp.route('/')
def index():
    return render_template('index.html')

@blp.route('/education')
def education():
    badges = all_badges()
    return render_template('education.html', badges=badges)

@blp.route('/portfolio')
def portfolio():
    projects = all_projects()
    return render_template('portfolio.html', projects=projects)

@blp.route('/contact', methods=('GET','POST'))
def contact():
    form = ContactForm()
    if request.method == 'POST' and form.validate_on_submit():
        contact = form.contact.data
        subject = form.subject.data
        message = form.message.data

        send_email(os.environ['DEFAULT_MAIL_SENDER'], subject, 'email/contact', contact=contact, message=message)
        flash('Message has been sent!', 'success')
        return redirect('contact')
    
    if form.errors:
        for error, message in form.errors.items():
            flash(message[0], 'warning')
            return render_template('contact.html', form=form)

    return render_template('contact.html', form=form)

app/templates/admin-page.html
{% extends 'base.html' %}
{% block content %}

    <form method="POST"
        action="{{url_for('admin_blueprint.admin_page')}}">
        <fieldset><legend>Portfolio Project</legend>
            <div class="form-grid">
                {{form1.csrf_token}}
                {{form1.name.label}}
                {{form1.name()}}
                {{form1.link.label}}
                {{form1.link()}}
                {{form1.description.label}}
                {{form1.description()}}
                {{form1.submit()}}
            </div>
        </fieldset>
    </form>

    <form method="POST"
        enctype="multipart/form-data"
        action="{{url_for('admin_blueprint.admin_page')}}">
        <fieldset><legend>Credly Badge</legend>
            <div class="form-grid">
                {{form2.csrf_token}}
                {{form2.name.label}}
                {{form2.name()}}
                {{form2.link.label}}
                {{form2.link()}}
                {{form2.image.label}}
                {{form2.image()}}
                {{form2.submit()}}
            </div>
        </fieldset>
    </form>

{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<!--
  Author: Bo Hendrix Parker
  Date: 03/10/2022
  Filename: index.html
-->
<html lang="en">
<head>
  <title>About Me</title>
  <meta charset="utf-8">
  <link rel="stylesheet" href="{{url_for('static', filename='css/styles.css')}}">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Insert Favicons -->
  <link rel="icon" href="{{url_for('static', filename='images/favicons/favicon.png')}}">
  <link rel="apple-touch-icon" sizes="180x180" href="{{url_for('static', filename='images/favicons/apple-touch-icon.png')}}">
</head>

<body>

  <div id="container">

    <header>

      <!-- Mobile Header -->
      <img src="{{url_for('static', filename='images/mobile-banner.png')}}" class="mobile-header mobile" alt="bhp mobile banner">

      <!-- Desktop Header -->
      <img src="{{url_for('static', filename='images/banner.png')}}" class="tab-desk desktop-header" alt="bhp banner">

    </header>

    <!-- mobile nav links -->
    <nav class="mobile-nav">
      <div id="menu-links">
        <a href="{{url_for('frontend_blueprint.index')}}">About Me</a>
        <a href="{{url_for('frontend_blueprint.education')}}">Education</a>
        <a href="{{url_for('frontend_blueprint.portfolio')}}">Portfolio</a>
        <a href="{{url_for('frontend_blueprint.contact')}}">Contact</a>
      </div>
      <!-- nav button -->
      <a class="nav-button" onclick="menu()">
        <div id="accordian">&#9776;</div>
      </a>
    </nav>
    
    <!-- nav for tablet and desktop -->
    <nav class="tab-desk">
      <ul>
      	<li><a href="{{url_for('frontend_blueprint.index')}}">About Me</a></li>
      	<li><a href="{{url_for('frontend_blueprint.education')}}">Education</a></li>
      	<li><a href="{{url_for('frontend_blueprint.portfolio')}}">Portfolio</a></li>
      	<li><a href="{{url_for('frontend_blueprint.contact')}}">Contact</a></li>
      </ul>
    </nav>

    <div>
      {% for category, message in get_flashed_messages
        (with_categories=true) %}
        <div class="flash-message {{category}}">
          {{message}}
        </div>
      {% endfor %}
    </div>

    {% block content %}{% endblock %}

    <footer>
        <p>Copyright &copy; 2023 Bo Hendrix Parker</p>
    </footer>
  
    </div>
  
  <script src="{{url_for('static', filename='scripts/script.js')}}"></script>
  </body>
  </html>

app/templates/contact.html
{% extends 'base.html' %}
{% block content %}
    <main>
      <h2 id="contact-descr">
        Send me a message if you would like any info and 
        I will get back to you ASAP!
      </h2>
      <form class="form" novalidate
        method="POST"
        action="{{url_for('frontend_blueprint.contact')}}">
        <fieldset><legend>Contact Form</legend>
        <div class="form-grid">
          {{ form.csrf_token }}
          {{ form.contact.label }}
          {{ form.contact() }}
          {{ form.subject.label }}
          {{ form.subject() }}
          {{ form.message.label }}
          {{ form.message() }}
          {{ form.submit() }}
        </div>
      </fieldset>
      </form>
      <br>
      <hr>
      <h3>I am located in Spring Hill, Florida.</h3>
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d112219.47584107092!2d-82.61923864271328!3d28.483804105204438!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88c29e37215440a1%3A0x96d839eb30e182b8!2sSpring%20Hill%2C%20FL!5e0!3m2!1sen!2sus!4v1650754651040!5m2!1sen!2sus" allowfullscreen="" loading="lazy" class="map"></iframe>

    </main>
{% endblock %}

app/templates/education.html
{% from 'macros.html' import badge_macro with context %}
{% extends 'base.html' %}
{% block content %}
    <main>
      <h1>Education</h1>
      <article class="brief">
          
          <h3>Computer Programming and Analysis, Associate in Science</h3>
          <h4>GPA: 4.0 | Pasco Hernando State College</h4>
          <hr>
          <h4>Currently studying for Bachelor of Applied Science in Cybersecurity</h4>
          <br>
          <br>
      </article>

      <h3>Certifications and Badges</h3>

      <div class="certs-grid">

        {% for badge in badges %}

          {{ badge_macro(badge[0],badge[1],badge[2]) }}

        {% endfor %}
      </div>

      <h3>Udemy Certificates</h3>
      <div class="udemy-grid">

        <img src="{{url_for('static', filename='images/udemy/flask-smorest.jpg')}}" alt="flask-smorest-certificate">
        <img src="{{url_for('static', filename='images/udemy/python-postgres.jpg')}}" alt="python-postgresql-certificate">


      </div>
    </main>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% block content %}
    <main>
      <h1>About Me</h1>
      <article class="brief">
        <p>I am a full time student at Pasco Hernando State College. 
          I will graduate with an Associate's Degree in Computer Programming 
        and Analysis on May 4th, 2023. I will then continue my education 
        by pursuing a BAS in Cyber Security.</p>
        <p>
          I have focused on learning Python development in my free time. 
          I am fluent with the Flask framework, REST APIs using Flask-Smorest, 
          SQL, particularly PostgreSQL, git, HTML5, and CSS.
        </p>
        <p>I have many certifications and hope to pursue a career in 
          DevOps or Administration. Please checkout my 
          <a class="in-text-link" href="{{url_for('frontend_blueprint.portfolio')}}">Portfolio page</a> 
          to see the projects I've worked on or my 
          <a class="in-text-link" href="{{url_for('frontend_blueprint.education')}}">Education page</a>
          to see my degree and the many certifications I have.
        </p>
      </article>

      <section id="profiles">
        <h1>Profiles</h1>
        <div id="profiles-grid">
          
          <a href="https://github.com/bohparker" target="_blank">
            <article class="profiles-article">
              <section class="profile-img">
                <img src="{{url_for('static', filename='images/profiles/github.png')}}" alt="github logo">
              </section>
              <section class="profile-name">GitHub</section>
            </article>
          </a>

          <a href="https://www.credly.com/users/bo-parker/badges" target="_blank">
            <article class="profiles-article">
              <section class="profile-img">
                <img src="{{url_for('static', filename='images/profiles/credly.png')}}" alt="credly logo">
              </section>
              <section class="profile-name">Credly</section>
            </article>
          </a>

          <a href="https://www.linkedin.com/in/bo-parker/" target="_blank">
            <article class="profiles-article">
              <section class="profile-img">
                <img src="{{url_for('static', filename='images/profiles/linkedin.png')}}" alt="linkedin logo">
              </section>
              <section class="profile-name">LinkedIn</section>
            </article>
          </a>

          <a href="https://www.udemy.com/user/bo-hendrix-parker/" target="_blank">
            <article class="profiles-article">
              <section class="profile-img">
                <img src="{{url_for('static', filename='images/profiles/udemy.png')}}" alt="udemy logo">
              </section>
              <section class="profile-name">Udemy</section>
            </article>
          </a>

        </div>
      </section>

    </main>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% block content %}

    <form method="POST"
        action="{{url_for('admin_blueprint.login')}}">
        <fieldset><legend>Login</legend>
            <div class="form-grid">
                {{form.csrf_token}}
                {{form.username.label}}
                {{form.username()}}
                {{form.password.label}}
                {{form.password()}}
                {{form.submit()}}
            </div>
        </fieldset>
    </form>

{% endblock %}

app/templates/macros.html
{% macro project_macro(name,link,description) %}

    <article class="portfolio-article">
        <a class="githublink" href="{{link}}" target="_blank">View on Github</a>
        <h3>{{name}}</h3>
        <p>{{description}}</p>
    </article>   

{% endmacro %}

{% macro badge_macro(name,link,filename) %}

    <article class="cert">
        <a href="{{link}}" target="_blank">
            <img src="{{url_for('static', filename='images/badges/')}}{{filename}}" alt="{{name}}">
        </a>
    </article>

{% endmacro %}

app/templates/portfolio.html
{% from 'macros.html' import project_macro with context %}
{% extends 'base.html' %}
{% block content %}
    <main>
      <h1>Portfolio</h1>
      <div class="grid2">
      
        {% for project in projects %}

          {{ project_macro(project[0],project[1],project[2]) }}

        {% endfor %}

      </div>
    </main>
{% endblock %}